alias ls='ls --color=auto'
alias grep='grep --colour=auto'
alias reboot='sudo reboot'
alias halt='sudo halt'
alias acpitool='sudo acpitool'
alias make='nice -n20 make -j4'
alias ccache='CCACHE_DIR=/var/tmp/ccache ccache'
alias wgc='wget -c'
alias straxil='ssh gogo@straxil'
alias on='ssh-add -t 1800'
alias off='ssh-add -D'
alias l='ls -l'
alias la='ls -al'
alias v='vim'
alias s='sudo'
alias t='tmux'
alias ta='tmux attach'
alias revdep='sudo nice -n20 revdep-rebuild'
alias ctorrent='ctorrent -p 33222'
alias mem='sudo zsh -c "echo mem > /sys/power/state"'
alias disk='sudo zsh -c "echo disk > /sys/power/state"'
alias a='sudo apt-get'
alias ac='sudo apt-cache'
alias godaddy='ssh imagenation@godaddy'
alias amzn-dev='ssh imagenation@development'
alias amzn-staging='ssh imagenation@staging'
alias amzn-release='ssh imagenation@release'
alias imagenation-build='ssh gogo@imagenation-build'
alias amzn-db='ssh imagenation@database'

