alias a='sudo apt-get'
alias ac='sudo apt-cache'
alias amzn-db='ssh imagenation@database'
alias amzn-dev='ssh imagenation@development'
alias amzn-release='ssh imagenation@release'
alias amzn-staging='ssh imagenation@staging'
alias g="git"
alias godaddy='ssh imagenation@godaddy'
alias grep='grep --colour=auto'
alias halt='sudo halt'
alias imagenation-build='ssh gogo@imagenation-build'
alias l='ls -l'
alias la='ls -al'
alias ls='ls --color=auto'
alias make='nice -n20 make -j4'
alias off='ssh-add -D'
alias on='ssh-add -t 1800'
alias reboot='sudo reboot'
alias s='sudo'
alias sd='svn diff'
alias sp='svn up'
alias straxil='ssh gogo@straxil'
alias sv='sudo vim'
alias t='tmux'
alias ta='tmux attach'
alias v='vim'
alias wgc='wget -c'
